version: '3'
networks:
  default:
    external:
      name: mynetwork

services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    volumes:
      - ~/.docker/volumes/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    security_opt:
    - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: 'root1234'
      MYSQL_USER: 'app_safbi'
      MYSQL_PASSWORD: '1234567890'
      MYSQL_DATABASE: 'safbi'

  safbi:
    container_name: safbi
    restart: always
    image: safbi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7007:7007
    environment:
      APP_SETTINGS: safbi.config.Docker
    depends_on:
      - mysql

