{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helmproj.fullname" . }}-secrets-vars
data:
  {{- range $key, $value := .Values.secrets.vars }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
