{{- if .Values.secrets.files }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helmproj.fullname" . }}-secrets-files
data:
{{- range $key, $value := .Values.secrets.files }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
